Imports CollegeBoardDLL

Public Class NoticeDisplaySettings
    Inherits System.Web.UI.Page

#Region " Web Form Designer Generated Code "

    'This call is required by the Web Form Designer.
    <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()

    End Sub
    Protected WithEvents Label7 As System.Web.UI.WebControls.Label
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents rowForeColor As System.Web.UI.WebControls.DropDownList
    Protected WithEvents DrpFontSizeRow As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Table1 As System.Web.UI.WebControls.Table
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
    Protected WithEvents rowFontName As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label6 As System.Web.UI.WebControls.Label
    Protected WithEvents rowBackColor As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents rbMessage As System.Web.UI.WebControls.Image
    Protected WithEvents rbMesg As System.Web.UI.WebControls.RadioButton
    Protected WithEvents Image5 As System.Web.UI.WebControls.Image
    Protected WithEvents rbAlert As System.Web.UI.WebControls.RadioButton
    Protected WithEvents Image2 As System.Web.UI.WebControls.Image
    Protected WithEvents rbRight As System.Web.UI.WebControls.RadioButton
    Protected WithEvents Image4 As System.Web.UI.WebControls.Image
    Protected WithEvents rbNew As System.Web.UI.WebControls.RadioButton
    Protected WithEvents Image1 As System.Web.UI.WebControls.Image
    Protected WithEvents rbHand As System.Web.UI.WebControls.RadioButton
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents Button2 As System.Web.UI.WebControls.Button
    Protected WithEvents Button3 As System.Web.UI.WebControls.Button
    Protected WithEvents rbNone As System.Web.UI.WebControls.RadioButton

    'NOTE: The following placeholder declaration is required by the Web Form Designer.
    'Do not delete or move it.
    Private designerPlaceholderDeclaration As System.Object

    Private Sub Page_Init(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Init
        'CODEGEN: This method call is required by the Web Form Designer
        'Do not modify it using the code editor.
        InitializeComponent()
    End Sub

#End Region

#Region "Class Variables"
    Dim sThForecolor, sThBackcolor, sTbackcolor, sTbordercolor, sRowbackcolor, sRowForecolor, rAlert, rBullet As String
    Dim iThFontsize, iRowfontsize As Integer
    Dim sThfamiliy, sRowfamily, sAlert, sBullet As String
    Dim objMessage As ClsMessageBoard
    Dim MSGSLNO As String


#End Region


    Private Sub Page_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Try

            If Not IsPostBack Then
                FormInfo(Session("USERSLNO"), Session("USERLOGSLNO"), System.Reflection.MethodBase.GetCurrentMethod().ReflectedType.FullName)
                MSGSLNO = Request.QueryString("MSGSLNO")
                Session("MSGSLNO") = MSGSLNO
            Else
                MSGSLNO = Session("MSGSLNO")

            End If
            AddFonts()

        Catch ex As Exception
            Throw ex
        End Try
        

    End Sub


    Private Sub AddFonts()
        Try

            Dim Fonts As New System.Drawing.Text.InstalledFontCollection
            Dim Family As FontFamily
            For Each Family In Fonts.Families
                ''THFontName.Items.Add(Family.Name)
                rowFontName.Items.Add(Family.Name)
            Next
            Dim i As Integer
            For i = 8 To 35
                ''THFontSize.Items.Add(i)
                DrpFontSizeRow.Items.Add(i)

            Next

            AddrowBackColor()
            AddrowForeColor()

        Catch ex As Exception
            Throw ex
        End Try
        ' Get the installed fonts collection.
       

    End Sub

    'Private Function AddHedForeColor()

    '    ThForeColor.Items.Add("AliceBlue")
    '    ThForeColor.Items.Add("Aqua")
    '    ThForeColor.Items.Add("Aquamarine")
    '    ThForeColor.Items.Add("Azure")
    '    ThForeColor.Items.Add("Beige")
    '    ThForeColor.Items.Add("Bisque")
    '    ThForeColor.Items.Add("Black")
    '    ThForeColor.Items.Add("BlanchedAlmond")
    '    ThForeColor.Items.Add("Blue")
    '    ThForeColor.Items.Add("BlueViolet")
    '    ThForeColor.Items.Add("Brown")
    '    ThForeColor.Items.Add("BurlyWood")
    '    ThForeColor.Items.Add("CadetBlue")
    '    ThForeColor.Items.Add("Chartreuse")
    '    ThForeColor.Items.Add("Chocolate")
    '    ThForeColor.Items.Add("Coral")
    '    ThForeColor.Items.Add("CornflowerBlue")
    '    ThForeColor.Items.Add("Cornsilk")
    '    ThForeColor.Items.Add("Crimson")
    '    ThForeColor.Items.Add("Cyan")
    '    ThForeColor.Items.Add("DarkBlue")
    '    ThForeColor.Items.Add("DarkCyan")
    '    ThForeColor.Items.Add("DarkGoldenrod")
    '    ThForeColor.Items.Add("DarkGray")
    '    ThForeColor.Items.Add("DarkGreen")
    '    ThForeColor.Items.Add("DarkKhaki")
    '    ThForeColor.Items.Add("DarkMagenta")
    '    ThForeColor.Items.Add("DarkOliveGreen")
    '    ThForeColor.Items.Add("DarkOrange")
    '    ThForeColor.Items.Add("DarkOrchid")
    '    ThForeColor.Items.Add("DarkRed")
    '    ThForeColor.Items.Add("DarkSalmon")
    '    ThForeColor.Items.Add("DarkSeaGreen")
    '    ThForeColor.Items.Add("DarkSlateBlue")
    '    ThForeColor.Items.Add("DarkSlateGray")
    '    ThForeColor.Items.Add("DarkTurquoise")
    '    ThForeColor.Items.Add("DarkViolet")
    '    ThForeColor.Items.Add("DeepPink")
    '    ThForeColor.Items.Add("DeepSkyBlue")
    '    ThForeColor.Items.Add("DimGray")
    '    ThForeColor.Items.Add("DodgerBlue")
    '    ThForeColor.Items.Add("Firebrick")
    '    ThForeColor.Items.Add("FloralWhite")
    '    ThForeColor.Items.Add("ForestGreen")
    '    ThForeColor.Items.Add("Fuchsia")
    '    ThForeColor.Items.Add("Gainsboro")
    '    ThForeColor.Items.Add("GhostWhite")
    '    ThForeColor.Items.Add("Gold")
    '    ThForeColor.Items.Add("Goldenrod")
    '    ThForeColor.Items.Add("Gray")
    '    ThForeColor.Items.Add("Green")
    '    ThForeColor.Items.Add("GreenYellow")
    '    ThForeColor.Items.Add("Honeydew")
    '    ThForeColor.Items.Add("HotPink")
    '    ThForeColor.Items.Add("IndianRed")
    '    ThForeColor.Items.Add("Indigo")
    '    ThForeColor.Items.Add("Ivory")
    '    ThForeColor.Items.Add("Khaki")
    '    ThForeColor.Items.Add("Lavender")
    '    ThForeColor.Items.Add("LavenderBlush")
    '    ThForeColor.Items.Add("LawnGreen")
    '    ThForeColor.Items.Add("LemonChiffon")
    '    ThForeColor.Items.Add("LightBlue")
    '    ThForeColor.Items.Add("LightCoral")
    '    ThForeColor.Items.Add("LightCyan")
    '    ThForeColor.Items.Add("LightGoldenrodYellow")
    '    ThForeColor.Items.Add("LightGray")
    '    ThForeColor.Items.Add("LightGreen")
    '    ThForeColor.Items.Add("LightPink")
    '    ThForeColor.Items.Add("LightSalmon")
    '    ThForeColor.Items.Add("LightSeaGreen")
    '    ThForeColor.Items.Add("LightSkyBlue")
    '    ThForeColor.Items.Add("LightSlateGray")
    '    ThForeColor.Items.Add("LightSteelBlue")
    '    ThForeColor.Items.Add("LightYellow")
    '    ThForeColor.Items.Add("Lime")
    '    ThForeColor.Items.Add("LimeGreen")
    '    ThForeColor.Items.Add("Linen")
    '    ThForeColor.Items.Add("Magenta")
    '    ThForeColor.Items.Add("Maroon")
    '    ThForeColor.Items.Add("MediumAquamarine")
    '    ThForeColor.Items.Add("MediumBlue")
    '    ThForeColor.Items.Add("MediumOrchid")
    '    ThForeColor.Items.Add("MediumPurple")
    '    ThForeColor.Items.Add("MediumSeaGreen")
    '    ThForeColor.Items.Add("MediumSlateBlue")
    '    ThForeColor.Items.Add("MediumSpringGreen")
    '    ThForeColor.Items.Add("MediumTurquoise")
    '    ThForeColor.Items.Add("MediumVioletRed")
    '    ThForeColor.Items.Add("MidnightBlue")
    '    ThForeColor.Items.Add("MintCream")
    '    ThForeColor.Items.Add("MistyRose")
    '    ThForeColor.Items.Add("Moccasin")
    '    ThForeColor.Items.Add("NavajoWhite")
    '    ThForeColor.Items.Add("Navy")
    '    ThForeColor.Items.Add("OldLace")
    '    ThForeColor.Items.Add("Olive")
    '    ThForeColor.Items.Add("OliveDrab")
    '    ThForeColor.Items.Add("Orange")
    '    ThForeColor.Items.Add("OrangeRed")
    '    ThForeColor.Items.Add("Orchid")
    '    ThForeColor.Items.Add("PaleGoldenrod")
    '    ThForeColor.Items.Add("PaleGreen")
    '    ThForeColor.Items.Add("PaleTurquoise")
    '    ThForeColor.Items.Add("PaleVioletRed")
    '    ThForeColor.Items.Add("PapayaWhip")
    '    ThForeColor.Items.Add("PeachPuff")
    '    ThForeColor.Items.Add("Peru")
    '    ThForeColor.Items.Add("Pink")
    '    ThForeColor.Items.Add("Plum")
    '    ThForeColor.Items.Add("PowderBlue")
    '    ThForeColor.Items.Add("Purple")
    '    ThForeColor.Items.Add("Red")
    '    ThForeColor.Items.Add("RosyBrown")
    '    ThForeColor.Items.Add("RoyalBlue")
    '    ThForeColor.Items.Add("SaddleBrown")
    '    ThForeColor.Items.Add("Salmon")
    '    ThForeColor.Items.Add("SandyBrown")
    '    ThForeColor.Items.Add("SeaGreen")
    '    ThForeColor.Items.Add("SeaShell")
    '    ThForeColor.Items.Add("Sienna")
    '    ThForeColor.Items.Add("Silver")
    '    ThForeColor.Items.Add("SkyBlue")
    '    ThForeColor.Items.Add("SlateBlue")
    '    ThForeColor.Items.Add("SlateGray")
    '    ThForeColor.Items.Add("Snow")
    '    ThForeColor.Items.Add("SpringGreen")
    '    ThForeColor.Items.Add("SteelBlue")
    '    ThForeColor.Items.Add("Tan")
    '    ThForeColor.Items.Add("Teal")
    '    ThForeColor.Items.Add("Thistle")
    '    ThForeColor.Items.Add("Tomato")
    '    ThForeColor.Items.Add("Transparent")
    '    ThForeColor.Items.Add("Turquoise")
    '    ThForeColor.Items.Add("Violet")
    '    ThForeColor.Items.Add("Wheat")
    '    ThForeColor.Items.Add("White")
    '    ThForeColor.Items.Add("WhiteSmoke")
    '    ThForeColor.Items.Add("Yellow")
    '    ThForeColor.Items.Add("YellowGreen")

    'End Function

    'Private Function AddHedBackColor()

    '    ThBackColor.Items.Add("AliceBlue")
    '    ThBackColor.Items.Add("Aqua")
    '    ThBackColor.Items.Add("Aquamarine")
    '    ThBackColor.Items.Add("Azure")
    '    ThBackColor.Items.Add("Beige")
    '    ThBackColor.Items.Add("Bisque")
    '    ThBackColor.Items.Add("Black")
    '    ThBackColor.Items.Add("BlanchedAlmond")
    '    ThBackColor.Items.Add("Blue")
    '    ThBackColor.Items.Add("BlueViolet")
    '    ThBackColor.Items.Add("Brown")
    '    ThBackColor.Items.Add("BurlyWood")
    '    ThBackColor.Items.Add("CadetBlue")
    '    ThBackColor.Items.Add("Chartreuse")
    '    ThBackColor.Items.Add("Chocolate")
    '    ThBackColor.Items.Add("Coral")
    '    ThBackColor.Items.Add("CornflowerBlue")
    '    ThBackColor.Items.Add("Cornsilk")
    '    ThBackColor.Items.Add("Crimson")
    '    ThBackColor.Items.Add("Cyan")
    '    ThBackColor.Items.Add("DarkBlue")
    '    ThBackColor.Items.Add("DarkCyan")
    '    ThBackColor.Items.Add("DarkGoldenrod")
    '    ThBackColor.Items.Add("DarkGray")
    '    ThBackColor.Items.Add("DarkGreen")
    '    ThBackColor.Items.Add("DarkKhaki")
    '    ThBackColor.Items.Add("DarkMagenta")
    '    ThBackColor.Items.Add("DarkOliveGreen")
    '    ThBackColor.Items.Add("DarkOrange")
    '    ThBackColor.Items.Add("DarkOrchid")
    '    ThBackColor.Items.Add("DarkRed")
    '    ThBackColor.Items.Add("DarkSalmon")
    '    ThBackColor.Items.Add("DarkSeaGreen")
    '    ThBackColor.Items.Add("DarkSlateBlue")
    '    ThBackColor.Items.Add("DarkSlateGray")
    '    ThBackColor.Items.Add("DarkTurquoise")
    '    ThBackColor.Items.Add("DarkViolet")
    '    ThBackColor.Items.Add("DeepPink")
    '    ThBackColor.Items.Add("DeepSkyBlue")
    '    ThBackColor.Items.Add("DimGray")
    '    ThBackColor.Items.Add("DodgerBlue")
    '    ThBackColor.Items.Add("Firebrick")
    '    ThBackColor.Items.Add("FloralWhite")
    '    ThBackColor.Items.Add("ForestGreen")
    '    ThBackColor.Items.Add("Fuchsia")
    '    ThBackColor.Items.Add("Gainsboro")
    '    ThBackColor.Items.Add("GhostWhite")
    '    ThBackColor.Items.Add("Gold")
    '    ThBackColor.Items.Add("Goldenrod")
    '    ThBackColor.Items.Add("Gray")
    '    ThBackColor.Items.Add("Green")
    '    ThBackColor.Items.Add("GreenYellow")
    '    ThBackColor.Items.Add("Honeydew")
    '    ThBackColor.Items.Add("HotPink")
    '    ThBackColor.Items.Add("IndianRed")
    '    ThBackColor.Items.Add("Indigo")
    '    ThBackColor.Items.Add("Ivory")
    '    ThBackColor.Items.Add("Khaki")
    '    ThBackColor.Items.Add("Lavender")
    '    ThBackColor.Items.Add("LavenderBlush")
    '    ThBackColor.Items.Add("LawnGreen")
    '    ThBackColor.Items.Add("LemonChiffon")
    '    ThBackColor.Items.Add("LightBlue")
    '    ThBackColor.Items.Add("LightCoral")
    '    ThBackColor.Items.Add("LightCyan")
    '    ThBackColor.Items.Add("LightGoldenrodYellow")
    '    ThBackColor.Items.Add("LightGray")
    '    ThBackColor.Items.Add("LightGreen")
    '    ThBackColor.Items.Add("LightPink")
    '    ThBackColor.Items.Add("LightSalmon")
    '    ThBackColor.Items.Add("LightSeaGreen")
    '    ThBackColor.Items.Add("LightSkyBlue")
    '    ThBackColor.Items.Add("LightSlateGray")
    '    ThBackColor.Items.Add("LightSteelBlue")
    '    ThBackColor.Items.Add("LightYellow")
    '    ThBackColor.Items.Add("Lime")
    '    ThBackColor.Items.Add("LimeGreen")
    '    ThBackColor.Items.Add("Linen")
    '    ThBackColor.Items.Add("Magenta")
    '    ThBackColor.Items.Add("Maroon")
    '    ThBackColor.Items.Add("MediumAquamarine")
    '    ThBackColor.Items.Add("MediumBlue")
    '    ThBackColor.Items.Add("MediumOrchid")
    '    ThBackColor.Items.Add("MediumPurple")
    '    ThBackColor.Items.Add("MediumSeaGreen")
    '    ThBackColor.Items.Add("MediumSlateBlue")
    '    ThBackColor.Items.Add("MediumSpringGreen")
    '    ThBackColor.Items.Add("MediumTurquoise")
    '    ThBackColor.Items.Add("MediumVioletRed")
    '    ThBackColor.Items.Add("MidnightBlue")
    '    ThBackColor.Items.Add("MintCream")
    '    ThBackColor.Items.Add("MistyRose")
    '    ThBackColor.Items.Add("Moccasin")
    '    ThBackColor.Items.Add("NavajoWhite")
    '    ThBackColor.Items.Add("Navy")
    '    ThBackColor.Items.Add("OldLace")
    '    ThBackColor.Items.Add("Olive")
    '    ThBackColor.Items.Add("OliveDrab")
    '    ThBackColor.Items.Add("Orange")
    '    ThBackColor.Items.Add("OrangeRed")
    '    ThBackColor.Items.Add("Orchid")
    '    ThBackColor.Items.Add("PaleGoldenrod")
    '    ThBackColor.Items.Add("PaleGreen")
    '    ThBackColor.Items.Add("PaleTurquoise")
    '    ThBackColor.Items.Add("PaleVioletRed")
    '    ThBackColor.Items.Add("PapayaWhip")
    '    ThBackColor.Items.Add("PeachPuff")
    '    ThBackColor.Items.Add("Peru")
    '    ThBackColor.Items.Add("Pink")
    '    ThBackColor.Items.Add("Plum")
    '    ThBackColor.Items.Add("PowderBlue")
    '    ThBackColor.Items.Add("Purple")
    '    ThBackColor.Items.Add("Red")
    '    ThBackColor.Items.Add("RosyBrown")
    '    ThBackColor.Items.Add("RoyalBlue")
    '    ThBackColor.Items.Add("SaddleBrown")
    '    ThBackColor.Items.Add("Salmon")
    '    ThBackColor.Items.Add("SandyBrown")
    '    ThBackColor.Items.Add("SeaGreen")
    '    ThBackColor.Items.Add("SeaShell")
    '    ThBackColor.Items.Add("Sienna")
    '    ThBackColor.Items.Add("Silver")
    '    ThBackColor.Items.Add("SkyBlue")
    '    ThBackColor.Items.Add("SlateBlue")
    '    ThBackColor.Items.Add("SlateGray")
    '    ThBackColor.Items.Add("Snow")
    '    ThBackColor.Items.Add("SpringGreen")
    '    ThBackColor.Items.Add("SteelBlue")
    '    ThBackColor.Items.Add("Tan")
    '    ThBackColor.Items.Add("Teal")
    '    ThBackColor.Items.Add("Thistle")
    '    ThBackColor.Items.Add("Tomato")
    '    ThBackColor.Items.Add("Transparent")
    '    ThBackColor.Items.Add("Turquoise")
    '    ThBackColor.Items.Add("Violet")
    '    ThBackColor.Items.Add("Wheat")
    '    ThBackColor.Items.Add("White")
    '    ThBackColor.Items.Add("WhiteSmoke")
    '    ThBackColor.Items.Add("Yellow")
    '    ThBackColor.Items.Add("YellowGreen")

    'End Function
    'Private Function AddTableBorderColor()

    '    DrpTBorderColor.Items.Add("AliceBlue")
    '    DrpTBorderColor.Items.Add("Aqua")
    '    DrpTBorderColor.Items.Add("Aquamarine")
    '    DrpTBorderColor.Items.Add("Azure")
    '    DrpTBorderColor.Items.Add("Beige")
    '    DrpTBorderColor.Items.Add("Bisque")
    '    DrpTBorderColor.Items.Add("Black")
    '    DrpTBorderColor.Items.Add("BlanchedAlmond")
    '    DrpTBorderColor.Items.Add("Blue")
    '    DrpTBorderColor.Items.Add("BlueViolet")
    '    DrpTBorderColor.Items.Add("Brown")
    '    DrpTBorderColor.Items.Add("BurlyWood")
    '    DrpTBorderColor.Items.Add("CadetBlue")
    '    DrpTBorderColor.Items.Add("Chartreuse")
    '    DrpTBorderColor.Items.Add("Chocolate")
    '    DrpTBorderColor.Items.Add("Coral")
    '    DrpTBorderColor.Items.Add("CornflowerBlue")
    '    DrpTBorderColor.Items.Add("Cornsilk")
    '    DrpTBorderColor.Items.Add("Crimson")
    '    DrpTBorderColor.Items.Add("Cyan")
    '    DrpTBorderColor.Items.Add("DarkBlue")
    '    DrpTBorderColor.Items.Add("DarkCyan")
    '    DrpTBorderColor.Items.Add("DarkGoldenrod")
    '    DrpTBorderColor.Items.Add("DarkGray")
    '    DrpTBorderColor.Items.Add("DarkGreen")
    '    DrpTBorderColor.Items.Add("DarkKhaki")
    '    DrpTBorderColor.Items.Add("DarkMagenta")
    '    DrpTBorderColor.Items.Add("DarkOliveGreen")
    '    DrpTBorderColor.Items.Add("DarkOrange")
    '    DrpTBorderColor.Items.Add("DarkOrchid")
    '    DrpTBorderColor.Items.Add("DarkRed")
    '    DrpTBorderColor.Items.Add("DarkSalmon")
    '    DrpTBorderColor.Items.Add("DarkSeaGreen")
    '    DrpTBorderColor.Items.Add("DarkSlateBlue")
    '    DrpTBorderColor.Items.Add("DarkSlateGray")
    '    DrpTBorderColor.Items.Add("DarkTurquoise")
    '    DrpTBorderColor.Items.Add("DarkViolet")
    '    DrpTBorderColor.Items.Add("DeepPink")
    '    DrpTBorderColor.Items.Add("DeepSkyBlue")
    '    DrpTBorderColor.Items.Add("DimGray")
    '    DrpTBorderColor.Items.Add("DodgerBlue")
    '    DrpTBorderColor.Items.Add("Firebrick")
    '    DrpTBorderColor.Items.Add("FloralWhite")
    '    DrpTBorderColor.Items.Add("ForestGreen")
    '    DrpTBorderColor.Items.Add("Fuchsia")
    '    DrpTBorderColor.Items.Add("Gainsboro")
    '    DrpTBorderColor.Items.Add("GhostWhite")
    '    DrpTBorderColor.Items.Add("Gold")
    '    DrpTBorderColor.Items.Add("Goldenrod")
    '    DrpTBorderColor.Items.Add("Gray")
    '    DrpTBorderColor.Items.Add("Green")
    '    DrpTBorderColor.Items.Add("GreenYellow")
    '    DrpTBorderColor.Items.Add("Honeydew")
    '    DrpTBorderColor.Items.Add("HotPink")
    '    DrpTBorderColor.Items.Add("IndianRed")
    '    DrpTBorderColor.Items.Add("Indigo")
    '    DrpTBorderColor.Items.Add("Ivory")
    '    DrpTBorderColor.Items.Add("Khaki")
    '    DrpTBorderColor.Items.Add("Lavender")
    '    DrpTBorderColor.Items.Add("LavenderBlush")
    '    DrpTBorderColor.Items.Add("LawnGreen")
    '    DrpTBorderColor.Items.Add("LemonChiffon")
    '    DrpTBorderColor.Items.Add("LightBlue")
    '    DrpTBorderColor.Items.Add("LightCoral")
    '    DrpTBorderColor.Items.Add("LightCyan")
    '    DrpTBorderColor.Items.Add("LightGoldenrodYellow")
    '    DrpTBorderColor.Items.Add("LightGray")
    '    DrpTBorderColor.Items.Add("LightGreen")
    '    DrpTBorderColor.Items.Add("LightPink")
    '    DrpTBorderColor.Items.Add("LightSalmon")
    '    DrpTBorderColor.Items.Add("LightSeaGreen")
    '    DrpTBorderColor.Items.Add("LightSkyBlue")
    '    DrpTBorderColor.Items.Add("LightSlateGray")
    '    DrpTBorderColor.Items.Add("LightSteelBlue")
    '    DrpTBorderColor.Items.Add("LightYellow")
    '    DrpTBorderColor.Items.Add("Lime")
    '    DrpTBorderColor.Items.Add("LimeGreen")
    '    DrpTBorderColor.Items.Add("Linen")
    '    DrpTBorderColor.Items.Add("Magenta")
    '    DrpTBorderColor.Items.Add("Maroon")
    '    DrpTBorderColor.Items.Add("MediumAquamarine")
    '    DrpTBorderColor.Items.Add("MediumBlue")
    '    DrpTBorderColor.Items.Add("MediumOrchid")
    '    DrpTBorderColor.Items.Add("MediumPurple")
    '    DrpTBorderColor.Items.Add("MediumSeaGreen")
    '    DrpTBorderColor.Items.Add("MediumSlateBlue")
    '    DrpTBorderColor.Items.Add("MediumSpringGreen")
    '    DrpTBorderColor.Items.Add("MediumTurquoise")
    '    DrpTBorderColor.Items.Add("MediumVioletRed")
    '    DrpTBorderColor.Items.Add("MidnightBlue")
    '    DrpTBorderColor.Items.Add("MintCream")
    '    DrpTBorderColor.Items.Add("MistyRose")
    '    DrpTBorderColor.Items.Add("Moccasin")
    '    DrpTBorderColor.Items.Add("NavajoWhite")
    '    DrpTBorderColor.Items.Add("Navy")
    '    DrpTBorderColor.Items.Add("OldLace")
    '    DrpTBorderColor.Items.Add("Olive")
    '    DrpTBorderColor.Items.Add("OliveDrab")
    '    DrpTBorderColor.Items.Add("Orange")
    '    DrpTBorderColor.Items.Add("OrangeRed")
    '    DrpTBorderColor.Items.Add("Orchid")
    '    DrpTBorderColor.Items.Add("PaleGoldenrod")
    '    DrpTBorderColor.Items.Add("PaleGreen")
    '    DrpTBorderColor.Items.Add("PaleTurquoise")
    '    DrpTBorderColor.Items.Add("PaleVioletRed")
    '    DrpTBorderColor.Items.Add("PapayaWhip")
    '    DrpTBorderColor.Items.Add("PeachPuff")
    '    DrpTBorderColor.Items.Add("Peru")
    '    DrpTBorderColor.Items.Add("Pink")
    '    DrpTBorderColor.Items.Add("Plum")
    '    DrpTBorderColor.Items.Add("PowderBlue")
    '    DrpTBorderColor.Items.Add("Purple")
    '    DrpTBorderColor.Items.Add("Red")
    '    DrpTBorderColor.Items.Add("RosyBrown")
    '    DrpTBorderColor.Items.Add("RoyalBlue")
    '    DrpTBorderColor.Items.Add("SaddleBrown")
    '    DrpTBorderColor.Items.Add("Salmon")
    '    DrpTBorderColor.Items.Add("SandyBrown")
    '    DrpTBorderColor.Items.Add("SeaGreen")
    '    DrpTBorderColor.Items.Add("SeaShell")
    '    DrpTBorderColor.Items.Add("Sienna")
    '    DrpTBorderColor.Items.Add("Silver")
    '    DrpTBorderColor.Items.Add("SkyBlue")
    '    DrpTBorderColor.Items.Add("SlateBlue")
    '    DrpTBorderColor.Items.Add("SlateGray")
    '    DrpTBorderColor.Items.Add("Snow")
    '    DrpTBorderColor.Items.Add("SpringGreen")
    '    DrpTBorderColor.Items.Add("SteelBlue")
    '    DrpTBorderColor.Items.Add("Tan")
    '    DrpTBorderColor.Items.Add("Teal")
    '    DrpTBorderColor.Items.Add("Thistle")
    '    DrpTBorderColor.Items.Add("Tomato")
    '    DrpTBorderColor.Items.Add("Transparent")
    '    DrpTBorderColor.Items.Add("Turquoise")
    '    DrpTBorderColor.Items.Add("Violet")
    '    DrpTBorderColor.Items.Add("Wheat")
    '    DrpTBorderColor.Items.Add("White")
    '    DrpTBorderColor.Items.Add("WhiteSmoke")
    '    DrpTBorderColor.Items.Add("Yellow")
    '    DrpTBorderColor.Items.Add("YellowGreen")

    'End Function
    'Private Function AddTableBackColor()
    '    DrpTbackColor.Items.Add("AliceBlue")
    '    DrpTbackColor.Items.Add("Aqua")
    '    DrpTbackColor.Items.Add("Aquamarine")
    '    DrpTbackColor.Items.Add("Azure")
    '    DrpTbackColor.Items.Add("Beige")
    '    DrpTbackColor.Items.Add("Bisque")
    '    DrpTbackColor.Items.Add("Black")
    '    DrpTbackColor.Items.Add("BlanchedAlmond")
    '    DrpTbackColor.Items.Add("Blue")
    '    DrpTbackColor.Items.Add("BlueViolet")
    '    DrpTbackColor.Items.Add("Brown")
    '    DrpTbackColor.Items.Add("BurlyWood")
    '    DrpTbackColor.Items.Add("CadetBlue")
    '    DrpTbackColor.Items.Add("Chartreuse")
    '    DrpTbackColor.Items.Add("Chocolate")
    '    DrpTbackColor.Items.Add("Coral")
    '    DrpTbackColor.Items.Add("CornflowerBlue")
    '    DrpTbackColor.Items.Add("Cornsilk")
    '    DrpTbackColor.Items.Add("Crimson")
    '    DrpTbackColor.Items.Add("Cyan")
    '    DrpTbackColor.Items.Add("DarkBlue")
    '    DrpTbackColor.Items.Add("DarkCyan")
    '    DrpTbackColor.Items.Add("DarkGoldenrod")
    '    DrpTbackColor.Items.Add("DarkGray")
    '    DrpTbackColor.Items.Add("DarkGreen")
    '    DrpTbackColor.Items.Add("DarkKhaki")
    '    DrpTbackColor.Items.Add("DarkMagenta")
    '    DrpTbackColor.Items.Add("DarkOliveGreen")
    '    DrpTbackColor.Items.Add("DarkOrange")
    '    DrpTbackColor.Items.Add("DarkOrchid")
    '    DrpTbackColor.Items.Add("DarkRed")
    '    DrpTbackColor.Items.Add("DarkSalmon")
    '    DrpTbackColor.Items.Add("DarkSeaGreen")
    '    DrpTbackColor.Items.Add("DarkSlateBlue")
    '    DrpTbackColor.Items.Add("DarkSlateGray")
    '    DrpTbackColor.Items.Add("DarkTurquoise")
    '    DrpTbackColor.Items.Add("DarkViolet")
    '    DrpTbackColor.Items.Add("DeepPink")
    '    DrpTbackColor.Items.Add("DeepSkyBlue")
    '    DrpTbackColor.Items.Add("DimGray")
    '    DrpTbackColor.Items.Add("DodgerBlue")
    '    DrpTbackColor.Items.Add("Firebrick")
    '    DrpTbackColor.Items.Add("FloralWhite")
    '    DrpTbackColor.Items.Add("ForestGreen")
    '    DrpTbackColor.Items.Add("Fuchsia")
    '    DrpTbackColor.Items.Add("Gainsboro")
    '    DrpTbackColor.Items.Add("GhostWhite")
    '    DrpTbackColor.Items.Add("Gold")
    '    DrpTbackColor.Items.Add("Goldenrod")
    '    DrpTbackColor.Items.Add("Gray")
    '    DrpTbackColor.Items.Add("Green")
    '    DrpTbackColor.Items.Add("GreenYellow")
    '    DrpTbackColor.Items.Add("Honeydew")
    '    DrpTbackColor.Items.Add("HotPink")
    '    DrpTbackColor.Items.Add("IndianRed")
    '    DrpTbackColor.Items.Add("Indigo")
    '    DrpTbackColor.Items.Add("Ivory")
    '    DrpTbackColor.Items.Add("Khaki")
    '    DrpTbackColor.Items.Add("Lavender")
    '    DrpTbackColor.Items.Add("LavenderBlush")
    '    DrpTbackColor.Items.Add("LawnGreen")
    '    DrpTbackColor.Items.Add("LemonChiffon")
    '    DrpTbackColor.Items.Add("LightBlue")
    '    DrpTbackColor.Items.Add("LightCoral")
    '    DrpTbackColor.Items.Add("LightCyan")
    '    DrpTbackColor.Items.Add("LightGoldenrodYellow")
    '    DrpTbackColor.Items.Add("LightGray")
    '    DrpTbackColor.Items.Add("LightGreen")
    '    DrpTbackColor.Items.Add("LightPink")
    '    DrpTbackColor.Items.Add("LightSalmon")
    '    DrpTbackColor.Items.Add("LightSeaGreen")
    '    DrpTbackColor.Items.Add("LightSkyBlue")
    '    DrpTbackColor.Items.Add("LightSlateGray")
    '    DrpTbackColor.Items.Add("LightSteelBlue")
    '    DrpTbackColor.Items.Add("LightYellow")
    '    DrpTbackColor.Items.Add("Lime")
    '    DrpTbackColor.Items.Add("LimeGreen")
    '    DrpTbackColor.Items.Add("Linen")
    '    DrpTbackColor.Items.Add("Magenta")
    '    DrpTbackColor.Items.Add("Maroon")
    '    DrpTbackColor.Items.Add("MediumAquamarine")
    '    DrpTbackColor.Items.Add("MediumBlue")
    '    DrpTbackColor.Items.Add("MediumOrchid")
    '    DrpTbackColor.Items.Add("MediumPurple")
    '    DrpTbackColor.Items.Add("MediumSeaGreen")
    '    DrpTbackColor.Items.Add("MediumSlateBlue")
    '    DrpTbackColor.Items.Add("MediumSpringGreen")
    '    DrpTbackColor.Items.Add("MediumTurquoise")
    '    DrpTbackColor.Items.Add("MediumVioletRed")
    '    DrpTbackColor.Items.Add("MidnightBlue")
    '    DrpTbackColor.Items.Add("MintCream")
    '    DrpTbackColor.Items.Add("MistyRose")
    '    DrpTbackColor.Items.Add("Moccasin")
    '    DrpTbackColor.Items.Add("NavajoWhite")
    '    DrpTbackColor.Items.Add("Navy")
    '    DrpTbackColor.Items.Add("OldLace")
    '    DrpTbackColor.Items.Add("Olive")
    '    DrpTbackColor.Items.Add("OliveDrab")
    '    DrpTbackColor.Items.Add("Orange")
    '    DrpTbackColor.Items.Add("OrangeRed")
    '    DrpTbackColor.Items.Add("Orchid")
    '    DrpTbackColor.Items.Add("PaleGoldenrod")
    '    DrpTbackColor.Items.Add("PaleGreen")
    '    DrpTbackColor.Items.Add("PaleTurquoise")
    '    DrpTbackColor.Items.Add("PaleVioletRed")
    '    DrpTbackColor.Items.Add("PapayaWhip")
    '    DrpTbackColor.Items.Add("PeachPuff")
    '    DrpTbackColor.Items.Add("Peru")
    '    DrpTbackColor.Items.Add("Pink")
    '    DrpTbackColor.Items.Add("Plum")
    '    DrpTbackColor.Items.Add("PowderBlue")
    '    DrpTbackColor.Items.Add("Purple")
    '    DrpTbackColor.Items.Add("Red")
    '    DrpTbackColor.Items.Add("RosyBrown")
    '    DrpTbackColor.Items.Add("RoyalBlue")
    '    DrpTbackColor.Items.Add("SaddleBrown")
    '    DrpTbackColor.Items.Add("Salmon")
    '    DrpTbackColor.Items.Add("SandyBrown")
    '    DrpTbackColor.Items.Add("SeaGreen")
    '    DrpTbackColor.Items.Add("SeaShell")
    '    DrpTbackColor.Items.Add("Sienna")
    '    DrpTbackColor.Items.Add("Silver")
    '    DrpTbackColor.Items.Add("SkyBlue")
    '    DrpTbackColor.Items.Add("SlateBlue")
    '    DrpTbackColor.Items.Add("SlateGray")
    '    DrpTbackColor.Items.Add("Snow")
    '    DrpTbackColor.Items.Add("SpringGreen")
    '    DrpTbackColor.Items.Add("SteelBlue")
    '    DrpTbackColor.Items.Add("Tan")
    '    DrpTbackColor.Items.Add("Teal")
    '    DrpTbackColor.Items.Add("Thistle")
    '    DrpTbackColor.Items.Add("Tomato")
    '    DrpTbackColor.Items.Add("Transparent")
    '    DrpTbackColor.Items.Add("Turquoise")
    '    DrpTbackColor.Items.Add("Violet")
    '    DrpTbackColor.Items.Add("Wheat")
    '    DrpTbackColor.Items.Add("White")
    '    DrpTbackColor.Items.Add("WhiteSmoke")
    '    DrpTbackColor.Items.Add("Yellow")
    '    DrpTbackColor.Items.Add("YellowGreen")

    'End Function

    Private Function AddrowBackColor()

        rowBackColor.Items.Add("AliceBlue")
        rowBackColor.Items.Add("Aqua")
        rowBackColor.Items.Add("Aquamarine")
        rowBackColor.Items.Add("Azure")
        rowBackColor.Items.Add("Beige")
        rowBackColor.Items.Add("Bisque")
        rowBackColor.Items.Add("Black")
        rowBackColor.Items.Add("BlanchedAlmond")
        rowBackColor.Items.Add("Blue")
        rowBackColor.Items.Add("BlueViolet")
        rowBackColor.Items.Add("Brown")
        rowBackColor.Items.Add("BurlyWood")
        rowBackColor.Items.Add("CadetBlue")
        rowBackColor.Items.Add("Chartreuse")
        rowBackColor.Items.Add("Chocolate")
        rowBackColor.Items.Add("Coral")
        rowBackColor.Items.Add("CornflowerBlue")
        rowBackColor.Items.Add("Cornsilk")
        rowBackColor.Items.Add("Crimson")
        rowBackColor.Items.Add("Cyan")
        rowBackColor.Items.Add("DarkBlue")
        rowBackColor.Items.Add("DarkCyan")
        rowBackColor.Items.Add("DarkGoldenrod")
        rowBackColor.Items.Add("DarkGray")
        rowBackColor.Items.Add("DarkGreen")
        rowBackColor.Items.Add("DarkKhaki")
        rowBackColor.Items.Add("DarkMagenta")
        rowBackColor.Items.Add("DarkOliveGreen")
        rowBackColor.Items.Add("DarkOrange")
        rowBackColor.Items.Add("DarkOrchid")
        rowBackColor.Items.Add("DarkRed")
        rowBackColor.Items.Add("DarkSalmon")
        rowBackColor.Items.Add("DarkSeaGreen")
        rowBackColor.Items.Add("DarkSlateBlue")
        rowBackColor.Items.Add("DarkSlateGray")
        rowBackColor.Items.Add("DarkTurquoise")
        rowBackColor.Items.Add("DarkViolet")
        rowBackColor.Items.Add("DeepPink")
        rowBackColor.Items.Add("DeepSkyBlue")
        rowBackColor.Items.Add("DimGray")
        rowBackColor.Items.Add("DodgerBlue")
        rowBackColor.Items.Add("Firebrick")
        rowBackColor.Items.Add("FloralWhite")
        rowBackColor.Items.Add("ForestGreen")
        rowBackColor.Items.Add("Fuchsia")
        rowBackColor.Items.Add("Gainsboro")
        rowBackColor.Items.Add("GhostWhite")
        rowBackColor.Items.Add("Gold")
        rowBackColor.Items.Add("Goldenrod")
        rowBackColor.Items.Add("Gray")
        rowBackColor.Items.Add("Green")
        rowBackColor.Items.Add("GreenYellow")
        rowBackColor.Items.Add("Honeydew")
        rowBackColor.Items.Add("HotPink")
        rowBackColor.Items.Add("IndianRed")
        rowBackColor.Items.Add("Indigo")
        rowBackColor.Items.Add("Ivory")
        rowBackColor.Items.Add("Khaki")
        rowBackColor.Items.Add("Lavender")
        rowBackColor.Items.Add("LavenderBlush")
        rowBackColor.Items.Add("LawnGreen")
        rowBackColor.Items.Add("LemonChiffon")
        rowBackColor.Items.Add("LightBlue")
        rowBackColor.Items.Add("LightCoral")
        rowBackColor.Items.Add("LightCyan")
        rowBackColor.Items.Add("LightGoldenrodYellow")
        rowBackColor.Items.Add("LightGray")
        rowBackColor.Items.Add("LightGreen")
        rowBackColor.Items.Add("LightPink")
        rowBackColor.Items.Add("LightSalmon")
        rowBackColor.Items.Add("LightSeaGreen")
        rowBackColor.Items.Add("LightSkyBlue")
        rowBackColor.Items.Add("LightSlateGray")
        rowBackColor.Items.Add("LightSteelBlue")
        rowBackColor.Items.Add("LightYellow")
        rowBackColor.Items.Add("Lime")
        rowBackColor.Items.Add("LimeGreen")
        rowBackColor.Items.Add("Linen")
        rowBackColor.Items.Add("Magenta")
        rowBackColor.Items.Add("Maroon")
        rowBackColor.Items.Add("MediumAquamarine")
        rowBackColor.Items.Add("MediumBlue")
        rowBackColor.Items.Add("MediumOrchid")
        rowBackColor.Items.Add("MediumPurple")
        rowBackColor.Items.Add("MediumSeaGreen")
        rowBackColor.Items.Add("MediumSlateBlue")
        rowBackColor.Items.Add("MediumSpringGreen")
        rowBackColor.Items.Add("MediumTurquoise")
        rowBackColor.Items.Add("MediumVioletRed")
        rowBackColor.Items.Add("MidnightBlue")
        rowBackColor.Items.Add("MintCream")
        rowBackColor.Items.Add("MistyRose")
        rowBackColor.Items.Add("Moccasin")
        rowBackColor.Items.Add("NavajoWhite")
        rowBackColor.Items.Add("Navy")
        rowBackColor.Items.Add("OldLace")
        rowBackColor.Items.Add("Olive")
        rowBackColor.Items.Add("OliveDrab")
        rowBackColor.Items.Add("Orange")
        rowBackColor.Items.Add("OrangeRed")
        rowBackColor.Items.Add("Orchid")
        rowBackColor.Items.Add("PaleGoldenrod")
        rowBackColor.Items.Add("PaleGreen")
        rowBackColor.Items.Add("PaleTurquoise")
        rowBackColor.Items.Add("PaleVioletRed")
        rowBackColor.Items.Add("PapayaWhip")
        rowBackColor.Items.Add("PeachPuff")
        rowBackColor.Items.Add("Peru")
        rowBackColor.Items.Add("Pink")
        rowBackColor.Items.Add("Plum")
        rowBackColor.Items.Add("PowderBlue")
        rowBackColor.Items.Add("Purple")
        rowBackColor.Items.Add("Red")
        rowBackColor.Items.Add("RosyBrown")
        rowBackColor.Items.Add("RoyalBlue")
        rowBackColor.Items.Add("SaddleBrown")
        rowBackColor.Items.Add("Salmon")
        rowBackColor.Items.Add("SandyBrown")
        rowBackColor.Items.Add("SeaGreen")
        rowBackColor.Items.Add("SeaShell")
        rowBackColor.Items.Add("Sienna")
        rowBackColor.Items.Add("Silver")
        rowBackColor.Items.Add("SkyBlue")
        rowBackColor.Items.Add("SlateBlue")
        rowBackColor.Items.Add("SlateGray")
        rowBackColor.Items.Add("Snow")
        rowBackColor.Items.Add("SpringGreen")
        rowBackColor.Items.Add("SteelBlue")
        rowBackColor.Items.Add("Tan")
        rowBackColor.Items.Add("Teal")
        rowBackColor.Items.Add("Thistle")
        rowBackColor.Items.Add("Tomato")
        rowBackColor.Items.Add("Transparent")
        rowBackColor.Items.Add("Turquoise")
        rowBackColor.Items.Add("Violet")
        rowBackColor.Items.Add("Wheat")
        rowBackColor.Items.Add("White")
        rowBackColor.Items.Add("WhiteSmoke")
        rowBackColor.Items.Add("Yellow")
        rowBackColor.Items.Add("YellowGreen")
    End Function

    Private Function AddrowForeColor()


        rowForeColor.Items.Add("AliceBlue")
        rowForeColor.Items.Add("Aqua")
        rowForeColor.Items.Add("Aquamarine")
        rowForeColor.Items.Add("Azure")
        rowForeColor.Items.Add("Beige")
        rowForeColor.Items.Add("Bisque")
        rowForeColor.Items.Add("Black")
        rowForeColor.Items.Add("BlanchedAlmond")
        rowForeColor.Items.Add("Blue")
        rowForeColor.Items.Add("BlueViolet")
        rowForeColor.Items.Add("Brown")
        rowForeColor.Items.Add("BurlyWood")
        rowForeColor.Items.Add("CadetBlue")
        rowForeColor.Items.Add("Chartreuse")
        rowForeColor.Items.Add("Chocolate")
        rowForeColor.Items.Add("Coral")
        rowForeColor.Items.Add("CornflowerBlue")
        rowForeColor.Items.Add("Cornsilk")
        rowForeColor.Items.Add("Crimson")
        rowForeColor.Items.Add("Cyan")
        rowForeColor.Items.Add("DarkBlue")
        rowForeColor.Items.Add("DarkCyan")
        rowForeColor.Items.Add("DarkGoldenrod")
        rowForeColor.Items.Add("DarkGray")
        rowForeColor.Items.Add("DarkGreen")
        rowForeColor.Items.Add("DarkKhaki")
        rowForeColor.Items.Add("DarkMagenta")
        rowForeColor.Items.Add("DarkOliveGreen")
        rowForeColor.Items.Add("DarkOrange")
        rowForeColor.Items.Add("DarkOrchid")
        rowForeColor.Items.Add("DarkRed")
        rowForeColor.Items.Add("DarkSalmon")
        rowForeColor.Items.Add("DarkSeaGreen")
        rowForeColor.Items.Add("DarkSlateBlue")
        rowForeColor.Items.Add("DarkSlateGray")
        rowForeColor.Items.Add("DarkTurquoise")
        rowForeColor.Items.Add("DarkViolet")
        rowForeColor.Items.Add("DeepPink")
        rowForeColor.Items.Add("DeepSkyBlue")
        rowForeColor.Items.Add("DimGray")
        rowForeColor.Items.Add("DodgerBlue")
        rowForeColor.Items.Add("Firebrick")
        rowForeColor.Items.Add("FloralWhite")
        rowForeColor.Items.Add("ForestGreen")
        rowForeColor.Items.Add("Fuchsia")
        rowForeColor.Items.Add("Gainsboro")
        rowForeColor.Items.Add("GhostWhite")
        rowForeColor.Items.Add("Gold")
        rowForeColor.Items.Add("Goldenrod")
        rowForeColor.Items.Add("Gray")
        rowForeColor.Items.Add("Green")
        rowForeColor.Items.Add("GreenYellow")
        rowForeColor.Items.Add("Honeydew")
        rowForeColor.Items.Add("HotPink")
        rowForeColor.Items.Add("IndianRed")
        rowForeColor.Items.Add("Indigo")
        rowForeColor.Items.Add("Ivory")
        rowForeColor.Items.Add("Khaki")
        rowForeColor.Items.Add("Lavender")
        rowForeColor.Items.Add("LavenderBlush")
        rowForeColor.Items.Add("LawnGreen")
        rowForeColor.Items.Add("LemonChiffon")
        rowForeColor.Items.Add("LightBlue")
        rowForeColor.Items.Add("LightCoral")
        rowForeColor.Items.Add("LightCyan")
        rowForeColor.Items.Add("LightGoldenrodYellow")
        rowForeColor.Items.Add("LightGray")
        rowForeColor.Items.Add("LightGreen")
        rowForeColor.Items.Add("LightPink")
        rowForeColor.Items.Add("LightSalmon")
        rowForeColor.Items.Add("LightSeaGreen")
        rowForeColor.Items.Add("LightSkyBlue")
        rowForeColor.Items.Add("LightSlateGray")
        rowForeColor.Items.Add("LightSteelBlue")
        rowForeColor.Items.Add("LightYellow")
        rowForeColor.Items.Add("Lime")
        rowForeColor.Items.Add("LimeGreen")
        rowForeColor.Items.Add("Linen")
        rowForeColor.Items.Add("Magenta")
        rowForeColor.Items.Add("Maroon")
        rowForeColor.Items.Add("MediumAquamarine")
        rowForeColor.Items.Add("MediumBlue")
        rowForeColor.Items.Add("MediumOrchid")
        rowForeColor.Items.Add("MediumPurple")
        rowForeColor.Items.Add("MediumSeaGreen")
        rowForeColor.Items.Add("MediumSlateBlue")
        rowForeColor.Items.Add("MediumSpringGreen")
        rowForeColor.Items.Add("MediumTurquoise")
        rowForeColor.Items.Add("MediumVioletRed")
        rowForeColor.Items.Add("MidnightBlue")
        rowForeColor.Items.Add("MintCream")
        rowForeColor.Items.Add("MistyRose")
        rowForeColor.Items.Add("Moccasin")
        rowForeColor.Items.Add("NavajoWhite")
        rowForeColor.Items.Add("Navy")
        rowForeColor.Items.Add("OldLace")
        rowForeColor.Items.Add("Olive")
        rowForeColor.Items.Add("OliveDrab")
        rowForeColor.Items.Add("Orange")
        rowForeColor.Items.Add("OrangeRed")
        rowForeColor.Items.Add("Orchid")
        rowForeColor.Items.Add("PaleGoldenrod")
        rowForeColor.Items.Add("PaleGreen")
        rowForeColor.Items.Add("PaleTurquoise")
        rowForeColor.Items.Add("PaleVioletRed")
        rowForeColor.Items.Add("PapayaWhip")
        rowForeColor.Items.Add("PeachPuff")
        rowForeColor.Items.Add("Peru")
        rowForeColor.Items.Add("Pink")
        rowForeColor.Items.Add("Plum")
        rowForeColor.Items.Add("PowderBlue")
        rowForeColor.Items.Add("Purple")
        rowForeColor.Items.Add("Red")
        rowForeColor.Items.Add("RosyBrown")
        rowForeColor.Items.Add("RoyalBlue")
        rowForeColor.Items.Add("SaddleBrown")
        rowForeColor.Items.Add("Salmon")
        rowForeColor.Items.Add("SandyBrown")
        rowForeColor.Items.Add("SeaGreen")
        rowForeColor.Items.Add("SeaShell")
        rowForeColor.Items.Add("Sienna")
        rowForeColor.Items.Add("Silver")
        rowForeColor.Items.Add("SkyBlue")
        rowForeColor.Items.Add("SlateBlue")
        rowForeColor.Items.Add("SlateGray")
        rowForeColor.Items.Add("Snow")
        rowForeColor.Items.Add("SpringGreen")
        rowForeColor.Items.Add("SteelBlue")
        rowForeColor.Items.Add("Tan")
        rowForeColor.Items.Add("Teal")
        rowForeColor.Items.Add("Thistle")
        rowForeColor.Items.Add("Tomato")
        rowForeColor.Items.Add("Transparent")
        rowForeColor.Items.Add("Turquoise")
        rowForeColor.Items.Add("Violet")
        rowForeColor.Items.Add("Wheat")
        rowForeColor.Items.Add("White")
        rowForeColor.Items.Add("WhiteSmoke")
        rowForeColor.Items.Add("Yellow")
        rowForeColor.Items.Add("YellowGreen")

    End Function


    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        Try
            getFormValues()
            addValuesToTable()

        Catch ex As Exception
            Throw ex
        End Try


    End Sub

    Private Function getFormValues()
        Try

            sRowbackcolor = rowBackColor.SelectedItem.Text
            sRowForecolor = rowForeColor.SelectedItem.Text
            iRowfontsize = DrpFontSizeRow.SelectedItem.Value
            sRowfamily = rowFontName.SelectedItem.Text

            If rbHand.Checked = True Then
                rBullet = "hand.gif"
            ElseIf rbRight.Checked = True Then
                rBullet = "noticeArrow.gif"
            ElseIf rbMesg.Checked = True Then
                rBullet = "msg.gif"
            End If


            If rbNew.Checked = True Then
                rAlert = "new_alert.gif"
            ElseIf rbAlert.Checked = True Then
                rAlert = "exclam.gif"
            End If
        Catch ex As Exception

            Throw ex

        End Try


    End Function

    Private Function addValuesToTable()
        Try

            Table1.Rows(2).Cells(0).BackColor = Color.FromName(sRowbackcolor)
            Table1.Rows(2).Cells(0).ForeColor = Color.FromName(sRowForecolor)
            Table1.Rows(2).Cells(0).Font.Size = FontUnit.Point(iRowfontsize)
            Table1.Rows(2).Cells(0).Font.Name = sRowfamily

        Catch ex As Exception
            Throw ex
        End Try



    End Function

    Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click

        Try
            getFormValues()
            Dim rowDispSettings As String
            rowDispSettings = sRowbackcolor & "," & sRowForecolor & "," & sRowfamily & "," & iRowfontsize & "," & rBullet & "," & rAlert
            objMessage = New ClsMessageBoard
            objMessage.MB_Message_Fonts(CInt(MSGSLNO), Session("USERSLNO"), rowDispSettings)


        Catch ex As Exception
            Throw ex
        End Try

        '' Button2.Attributes.Add("OnClick", "dispClose()")


    End Sub

    Private Sub Button3_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button3.Click

        Dim rowDispSettings As String

        rowDispSettings = ""

        objMessage = New ClsMessageBoard
        objMessage.MB_Message_Fonts(CInt(MSGSLNO), Session("USERSLNO"), rowDispSettings)


    End Sub
End Class
